services:
  - type: web
    name: sms-outreach-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: FIREBASE_CRED_PATH
        value: /opt/render/project/src/firebase-service-account.json
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: API_KEY
        sync: false
